
#define MMCOP_DEFAULT_SEED 1

#define MMCOP_DEFAULT_INITIAL_PRICE 10
#define MMCOP_DEFAULT_INITIAL_VARIANCE 0
#define MMCOP_DEFAULT_TIMESTEP 1
#define MMCOP_DEFAULT_DRIFT 1.01
#define MMCOP_DEFAULT_MEAN_REVERSION_SPEED 0.5
#define MMCOP_DEFAULT_MEAN_REVERSION_LEVEL 5
#define MMCOP_DEFAULT_VOLATILITY 2
#define MMCOP_DEFAULT_CORRELATION_FACTOR 0.5

#define MMCOP_DEFAULT_STRIKE_PRICE 50
#define MMCOP_DEFAULT_DISCOUNTING_RATE 0.95

#define MMCOP_OUTPUT_DIRECTORY_PREFIX "mmcop_output"
#define MMCOP_OUTPUT_FILE_PREFIX "all_paths_output"
