
#define MMCOP_DEFAULT_SEED 1
#define MMCOP_DEFAULT_INITIAL_PRICE 100
#define MMCOP_DEFAULT_INITIAL_LOG_DEVIATION 0
#define MMCOP_DEFAULT_MEAN 0.0001
#define MMCOP_DEFAULT_PERSISTENCE 0.1
#define MMCOP_DEFAULT_VOLATILITY 0.001

#define MMCOP_DEFAULT_STRIKE_PRICE 100
#define MMCOP_DEFAULT_DISCOUNTING_RATE 0.99

#define MMCOP_OUTPUT_DIRECTORY_PREFIX "mmcop_output"
#define MMCOP_OUTPUT_FILE_PREFIX "all_paths_output"
